"""empty message

Revision ID: 0c0108a1ef19
Revises: b20b16a2d529
Create Date: 2023-12-11 14:53:14.337250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c0108a1ef19'
down_revision = 'b20b16a2d529'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voucher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('voucher_admin', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voucher', schema=None) as batch_op:
        batch_op.drop_column('voucher_admin')

    # ### end Alembic commands ###
