"""empty message

Revision ID: b20b16a2d529
Revises: 
Create Date: 2023-12-11 00:16:10.618172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b20b16a2d529'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('station',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('station_name', sa.String(length=30), nullable=False),
    sa.Column('station_serial', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trip',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trip_date', sa.String(length=30), nullable=False),
    sa.Column('start', sa.String(length=30), nullable=False),
    sa.Column('dest', sa.String(length=30), nullable=False),
    sa.Column('trip_fare', sa.Integer(), nullable=False),
    sa.Column('trip_card', sa.Integer(), nullable=False),
    sa.Column('trip_user', sa.Integer(), nullable=False),
    sa.Column('trip_status', sa.String(length=30), nullable=False),
    sa.Column('payment_status', sa.String(length=30), nullable=False),
    sa.Column('trip_time', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('Fname', sa.String(length=30), nullable=True),
    sa.Column('Lname', sa.String(length=30), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('address', sa.String(length=30), nullable=True),
    sa.Column('aType', sa.String(length=30), nullable=False),
    sa.Column('aStatus', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('voucher',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('voucher_code', sa.String(length=30), nullable=False),
    sa.Column('voucher_amount', sa.Integer(), nullable=False),
    sa.Column('voucher_status', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('complains',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('complain', sa.Text(), nullable=False),
    sa.Column('reply', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pass_card',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('card_no', sa.Integer(), nullable=False),
    sa.Column('card_type', sa.String(length=30), nullable=False),
    sa.Column('card_balance', sa.Integer(), nullable=False),
    sa.Column('card_view', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_no')
    )
    op.create_table('refund',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('refund_amount', sa.Integer(), nullable=False),
    sa.Column('refund_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refund_status', sa.String(length=30), nullable=False),
    sa.Column('trip_user', sa.String(length=30), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trip.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recharge',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('wallet_type', sa.String(length=30), nullable=False),
    sa.Column('card_no', sa.Integer(), nullable=False),
    sa.Column('wallet_mobile', sa.String(length=30), nullable=False),
    sa.Column('trxid', sa.String(length=30), nullable=False),
    sa.Column('recharge_amount', sa.Integer(), nullable=False),
    sa.Column('recharge_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['pass_card.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recharge')
    op.drop_table('refund')
    op.drop_table('pass_card')
    op.drop_table('complains')
    op.drop_table('voucher')
    op.drop_table('user')
    op.drop_table('trip')
    op.drop_table('station')
    # ### end Alembic commands ###
